In [2]:
import numpy as np
import pandas as pd

In [3]:
movies = pd.read_csv('movies.csv')
credits = pd.read_csv('credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies = movies.merge(credits, on='title')

In [7]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [8]:
movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [9]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [10]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [11]:
movies.loc[:,'overview'] = movies.loc[:,'overview'].fillna('')

In [12]:
movies.duplicated().sum()

0

In [13]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [14]:
def convertToList(genres):
    genresList = []
    for genre in ast.literal_eval(genres):
        genresList.append(genre['name'])
    return genresList

In [15]:
import ast
ast.literal_eval(movies.iloc[0].genres)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [16]:
movies['genres'] = movies['genres'].apply(convertToList)

In [17]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [18]:
movies['keywords'] = movies['keywords'].apply(convertToList)

In [19]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [20]:
def getThreeCast(casts):
    castList = []
    count = 0
    for cast in ast.literal_eval(casts):
        if count == 3:
            break
        castList.append(cast['name'])
        count += 1
    return castList

In [21]:
movies['cast'] = movies['cast'].apply(getThreeCast)

In [22]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [23]:
def fetchDirector(crews):
    directorsList = []
    for crew in ast.literal_eval(crews):
        if crew['job'] == 'Director':
            directorsList.append(crew['name'])
    return directorsList

In [24]:
movies['crew'] = movies['crew'].apply(fetchDirector)

In [25]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [26]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [28]:
def removiewhiteSpace(contentList):
    i=0
    for content in contentList:
        crew = content.replace(" ","")
        contentList[i] = content
        i +=1
    return contentList

In [29]:
movies['genres'] =movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] =movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] =movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(removiewhiteSpace)

In [30]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron]

In [31]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [32]:
newMovieDataFrame = movies[['movie_id','title','tags']]

In [33]:
newMovieDataFrame.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [34]:
newMovieDataFrame.loc[:,'tags'] = newMovieDataFrame.loc[:,'tags'].apply(lambda x:" ".join(x))

C:\Users\kavit\AppData\Local\Temp\ipykernel_7132\4162031117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newMovieDataFrame.loc[:,'tags'] = newMovieDataFrame.loc[:,'tags'].apply(lambda x:" ".join(x))

In [35]:
newMovieDataFrame['tags'] = newMovieDataFrame['tags'].apply(lambda x:x.lower())

C:\Users\kavit\AppData\Local\Temp\ipykernel_7132\1602216423.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newMovieDataFrame['tags'] = newMovieDataFrame['tags'].apply(lambda x:x.lower())

In [36]:
import nltk

In [37]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [38]:
def stem(text):
    stemmedTextList = []
    
    for i in text.split():
        stemmedTextList.append(ps.stem(i))
    return " ".join(stemmedTextList)

In [39]:
newMovieDataFrame['tags'] = newMovieDataFrame['tags'].apply(stem)

C:\Users\kavit\AppData\Local\Temp\ipykernel_7132\2536922808.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newMovieDataFrame['tags'] = newMovieDataFrame['tags'].apply(stem)

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=5000, stop_words = "english")

In [41]:
featureVectors = vectorizer.fit_transform(newMovieDataFrame['tags']).toarray()

In [42]:
featureVectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [43]:
vectorizer.get_feature_names()

C:\Users\kavit\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrian',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alecbaldwin',
 'alejandro',
 'alex',
 'alexand',
 'alfr',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'ang',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'ann',
 'anna',
 'annabel',
 'annafari',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoin',
 'anton',
 'antonio',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'armstrong',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'aronofski',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'baltimor',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'basketball',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becker',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berg',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blake',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'bout',
 'bowman',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boyl',
 'boys',
 'brad',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brett',
 'brian',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewilli',
 'brutal',
 'bryan',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burton',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cain',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'camerondiaz',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannib',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carpent',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherin',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chan',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapman',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chopra',
 'chosen',
 'chowyun',
 'chri',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clint',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'clooney',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'codi',
 'coen',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collin',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'columbu',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'conrad',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'coppola',
 ...]

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
similarity = cosine_similarity(featureVectors)

In [46]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])

[(0, 1.0000000000000002),
 (2409, 0.28644594961577313),
 (1216, 0.27921779664372753),
 (3731, 0.2506402059138015),
 (507, 0.25016291953504993),
 (1204, 0.24140227479263376),
 (539, 0.24019223070763068),
 (582, 0.2396974985022249),
 (1194, 0.22880215766121476),
 (778, 0.22422426466543746),
 (4049, 0.2218800784900916),
 (2787, 0.21982600255746473),
 (1920, 0.21977383072747692),
 (172, 0.20965696734438366),
 (94, 0.20814536170751838),
 (322, 0.2051282051282051),
 (61, 0.2046468711716401),
 (972, 0.2046468711716401),
 (3609, 0.20174251088960077),
 (151, 0.20033416898825337),
 (4194, 0.20033416898825335),
 (1444, 0.20016019225635892),
 (74, 0.19985201625794738),
 (2333, 0.19985201625794738),
 (1089, 0.1981740732880975),
 (260, 0.1951231356683212),
 (577, 0.19512313566832118),
 (973, 0.19512313566832118),
 (47, 0.19418390934515437),
 (2204, 0.19312181983410703),
 (3676, 0.19312181983410703),
 (4000, 0.1921537845661046),
 (942, 0.18887686585995425),
 (2972, 0.18871283902409933),
 (1201, 0.18842228790639834),
 (4407, 0.18490006540840973),
 (3328, 0.18367958959266126),
 (27, 0.18302666282596894),
 (4, 0.18300360434867097),
 (305, 0.1815682598006407),
 (495, 0.1815682598006407),
 (1329, 0.1815682598006407),
 (2515, 0.1815682598006407),
 (1537, 0.18116432546313532),
 (1071, 0.17948717948717946),
 (168, 0.17295817388759027),
 (220, 0.17255919256291524),
 (1275, 0.17255919256291524),
 (83, 0.17118419700436519),
 (4338, 0.17093520167692652),
 (184, 0.1709352016769265),
 (1321, 0.1706971854997297),
 (931, 0.16984155512168933),
 (300, 0.16898159235484367),
 (36, 0.167093470609201),
 (373, 0.16694514082354447),
 (3163, 0.1667752796900333),
 (661, 0.1653796461189446),
 (3539, 0.16526725762745997),
 (1982, 0.16477051091432687),
 (529, 0.16349964255346808),
 (1831, 0.16349964255346808),
 (3000, 0.1634301126151534),
 (91, 0.16239958858823),
 (41, 0.1617875572323585),
 (150, 0.1611258466588724),
 (595, 0.1601281538050871),
 (342, 0.15818713475337637),
 (67, 0.15585730003983933),
 (3722, 0.15534712747612348),
 (4011, 0.15534712747612348),
 (581, 0.15408338784034142),
 (158, 0.1539670545751043),
 (502, 0.15253477177414312),
 (149, 0.15202972471705734),
 (1178, 0.15191090506255),
 (4780, 0.15191090506255),
 (31, 0.1513068831672006),
 (187, 0.1500468969841066),
 (1344, 0.1500468969841066),
 (1383, 0.1500468969841066),
 (513, 0.14824986333222023),
 (3148, 0.14792005232672775),
 (838, 0.146943671674129),
 (311, 0.14651588715165131),
 (111, 0.1465158871516513),
 (2732, 0.14617633655117152),
 (7, 0.14484136487558028),
 (1297, 0.14484136487558028),
 (1658, 0.1437993271357627),
 (2075, 0.1437993271357627),
 (2761, 0.1435161644183277),
 (1741, 0.14351616441832768),
 (52, 0.14322297480788657),
 (127, 0.14322297480788657),
 (1479, 0.14235407108686474),
 (26, 0.1416576493949657),
 (1396, 0.14121975762272052),
 (108, 0.1401425507601155),
 (1056, 0.1401425507601155),
 (1355, 0.1401425507601155),
 (1938, 0.1401425507601155),
 (1965, 0.14011213457945124),
 (466, 0.13977131156292244),
 (275, 0.13937366833451514),
 (294, 0.13937366833451514),
 (579, 0.13937366833451514),
 (3355, 0.13937366833451514),
 (95, 0.1386750490563073),
 (461, 0.1373087590952724),
 (568, 0.1373087590952724),
 (2496, 0.1373087590952724),
 (17, 0.13693937303317935),
 (490, 0.13655774839978377),
 (1488, 0.13655774839978377),
 (46, 0.13533299049019168),
 (232, 0.13533299049019168),
 (859, 0.13533299049019168),
 (4541, 0.1345345587992625),
 (249, 0.13355611265883557),
 (476, 0.13355611265883557),
 (1327, 0.13355611265883557),
 (3782, 0.13355611265883557),
 (3983, 0.13355611265883557),
 (72, 0.13344012817090595),
 (843, 0.13344012817090595),
 (1749, 0.13344012817090595),
 (2169, 0.13344012817090595),
 (3410, 0.13344012817090595),
 (1273, 0.13323467750529824),
 (4350, 0.13323467750529824),
 (1322, 0.1320989873168695),
 (777, 0.1319717610643751),
 (1560, 0.1316245316231641),
 (4080, 0.1316245316231641),
 (56, 0.1307440900921227),
 (105, 0.1307440900921227),
 (505, 0.1307440900921227),
 (668, 0.1307440900921227),
 (2584, 0.1307440900921227),
 (413, 0.12988108336653278),
 (1808, 0.12988108336653278),
 (589, 0.12955005512625914),
 (2133, 0.12955005512625914),
 (1015, 0.1282051282051282),
 (1373, 0.12810252304406972),
 (1774, 0.12810252304406972),
 (2378, 0.12810252304406972),
 (2714, 0.12725695259515554),
 (138, 0.12659242088545833),
 (1086, 0.12659242088545833),
 (2181, 0.12659242088545833),
 (3341, 0.12659242088545833),
 (889, 0.12622316656203794),
 (134, 0.12561485860426555),
 (368, 0.12561485860426555),
 (935, 0.12561485860426555),
 (2874, 0.12508145976752497),
 (3623, 0.12503908082008885),
 (14, 0.12503908082008883),
 (166, 0.1235415527768502),
 (937, 0.1235415527768502),
 (2687, 0.1235415527768502),
 (4232, 0.1235415527768502),
 (487, 0.12326671027227314),
 (773, 0.12326671027227314),
 (1833, 0.12326671027227314),
 (2971, 0.12326671027227314),
 (754, 0.1220965726263761),
 (126, 0.12209657262637608),
 (2450, 0.12209657262637608),
 (483, 0.12104550653376048),
 (1096, 0.12104550653376048),
 (1158, 0.12104550653376048),
 (2060, 0.12104550653376048),
 (84, 0.12104550653376046),
 (102, 0.12104550653376046),
 (1878, 0.12104550653376046),
 (557, 0.1207011373963169),
 (3629, 0.1207011373963169),
 (2480, 0.12009611535381534),
 (2881, 0.12009611535381534),
 (1299, 0.11935247900657214),
 (3236, 0.11935247900657214),
 (139, 0.11916871834484359),
 (68, 0.11894020669001051),
 (208, 0.11894020669001051),
 (781, 0.11894020669001051),
 (1004, 0.11894020669001051),
 (1301, 0.11894020669001051),
 (2652, 0.11894020669001051),
 (3377, 0.11894020669001051),
 (438, 0.1180480411624714),
 (2284, 0.1180480411624714),
 (1274, 0.11694106924093722),
 (4676, 0.11694106924093722),
 (369, 0.11678545896676293),
 (549, 0.11678545896676293),
 (900, 0.11678545896676293),
 (1715, 0.11651034560709261),
 (2675, 0.11651034560709261),
 (3084, 0.11651034560709261),
 (1002, 0.1165103456070926),
 (160, 0.11561170597113389),
 (11, 0.11556254088025608),
 (587, 0.11556254088025608),
 (870, 0.11556254088025608),
 (1617, 0.11556254088025608),
 (1047, 0.11503946170861017),
 (278, 0.11437725271791938),
 (2547, 0.11437725271791938),
 (2821, 0.11437725271791938),
 (3213, 0.11357879791107997),
 (1673, 0.11322770341445959),
 (2331, 0.11322770341445959),
 (2790, 0.11322770341445959),
 (279, 0.11322770341445958),
 (432, 0.11322770341445958),
 (454, 0.11322770341445958),
 (4345, 0.11322770341445958),
 (28, 0.11322770341445956),
 (122, 0.11322770341445956),
 (422, 0.11322770341445956),
 (2742, 0.11322770341445956),
 (1497, 0.11244949691847501),
 (1220, 0.11211213233271873),
 (238, 0.11168711865749101),
 (236, 0.11149893466761211),
 (678, 0.11149893466761211),
 (3444, 0.11102889792108188),
 (256, 0.11020775375559674),
 (808, 0.11020775375559674),
 (2323, 0.11020775375559674),
 (536, 0.10997646755364593),
 (420, 0.10997646755364592),
 (1418, 0.10997646755364592),
 (50, 0.10984700727621793),
 (1945, 0.10984700727621793),
 (85, 0.10938835388564894),
 (206, 0.10878565864408421),
 (87, 0.10826639239215334),
 (1616, 0.10826639239215334),
 (81, 0.108094949066235),
 (1574, 0.108094949066235),
 (1512, 0.10795837927188263),
 (182, 0.10795837927188262),
 (228, 0.10795837927188262),
 (2372, 0.10795837927188262),
 (189, 0.10741723110591492),
 (653, 0.10741723110591492),
 (1005, 0.10741723110591492),
 (1524, 0.10741723110591492),
 (4001, 0.10741723110591492),
 (692, 0.10699012312772824),
 (3310, 0.10699012312772824),
 (3631, 0.10699012312772824),
 (229, 0.10675210253672476),
 (21, 0.10675210253672475),
 (121, 0.10675210253672475),
 (227, 0.10675210253672475),
 (786, 0.10675210253672475),
 (1031, 0.10675210253672475),
 (2148, 0.10675210253672475),
 (3009, 0.10675210253672475),
 (3499, 0.10675210253672475),
 (4471, 0.10675210253672475),
 (939, 0.1060991783534611),
 (5, 0.10604746049596296),
 (143, 0.10604746049596296),
 (740, 0.10604746049596296),
 (1019, 0.10604746049596296),
 (3094, 0.10604746049596296),
 (307, 0.10591481821704041),
 (1037, 0.10529962529853128),
 (2072, 0.10529962529853128),
 (262, 0.105129283382795),
 (627, 0.10482848367219183),
 (1348, 0.10482848367219183),
 (3056, 0.10482848367219183),
 (541, 0.10423454980627082),
 (123, 0.10423454980627081),
 (170, 0.10423454980627081),
 (1496, 0.10423454980627081),
 (472, 0.10390486669322622),
 (1237, 0.10390486669322622),
 (3429, 0.10390486669322622),
 (467, 0.10336227882434038),
 (131, 0.10256410256410256),
 (223, 0.10256410256410256),
 (295, 0.10256410256410256),
 (332, 0.10256410256410256),
 (687, 0.10256410256410256),
 (2439, 0.1025115460130912),
 (200, 0.10241831129983783),
 (624, 0.10241831129983783),
 (1501, 0.10241831129983783),
 (1745, 0.10241831129983783),
 (2634, 0.10241831129983783),
 (3622, 0.10241831129983783),
 (654, 0.10168147934776052),
 (75, 0.10127393670836667),
 (1195, 0.10127393670836667),
 (1771, 0.10127393670836667),
 (3153, 0.10127393670836667),
 (4098, 0.10127393670836667),
 (491, 0.10087125544480038),
 (572, 0.10087125544480038),
 (1455, 0.10087125544480038),
 (2106, 0.10087125544480038),
 (2498, 0.10087125544480038),
 (233, 0.10016708449412667),
 (1166, 0.10016708449412667),
 (2161, 0.10016708449412667),
 (2456, 0.10016708449412667),
 (2521, 0.10016708449412667),
 (3664, 0.10016708449412667),
 (3840, 0.10016708449412667),
 (4136, 0.10016708449412667),
 (10, 0.10003126465607107),
 (312, 0.10003126465607107),
 (449, 0.10003126465607107),
 (643, 0.10003126465607107),
 (2818, 0.10003126465607107),
 (3756, 0.10003126465607107),
 (3875, 0.10003126465607107),
 (1634, 0.09962709627734358),
 (1439, 0.09930726528736966),
 (2099, 0.09930726528736966),
 (70, 0.09883324222148016),
 (1082, 0.09883324222148016),
 (1294, 0.09883324222148016),
 (363, 0.09855206599818042),
 (1405, 0.09855206599818042),
 (3442, 0.09855206599818042),
 (157, 0.09805806756909202),
 (1575, 0.09805806756909202),
 (1727, 0.09805806756909202),
 (2763, 0.09805806756909202),
 (2788, 0.09805806756909202),
 (3955, 0.09805806756909202),
 (330, 0.09767725810110087),
 (508, 0.09767725810110087),
 (510, 0.09767725810110087),
 (988, 0.09767725810110087),
 (1401, 0.09767725810110087),
 (1614, 0.09767725810110087),
 (2247, 0.09767725810110087),
 (3784, 0.09767725810110087),
 (266, 0.09656090991705352),
 (445, 0.09656090991705352),
 (1823, 0.09656090991705352),
 (2253, 0.09656090991705352),
 (3635, 0.09656090991705352),
 (3936, 0.09656090991705352),
 (35, 0.09607689228305229),
 (263, 0.09607689228305229),
 (319, 0.09607689228305229),
 (695, 0.09607689228305229),
 (1077, 0.09607689228305229),
 (1156, 0.09607689228305229),
 (4200, 0.09607689228305229),
 (1775, 0.0956948752938691),
 (410, 0.09548198320525772),
 (898, 0.09548198320525772),
 (1109, 0.09548198320525772),
 (2241, 0.09548198320525772),
 (230, 0.09501857794816083),
 (9, 0.09443843292997713),
 (334, 0.09443843292997713),
 (480, 0.09443843292997713),
 (535, 0.09443843292997713),
 (2556, 0.09443843292997713),
 (3256, 0.09443843292997713),
 (3356, 0.09443843292997713),
 (325, 0.09421114395319916),
 (878, 0.09421114395319916),
 (1027, 0.09421114395319916),
 (1280, 0.09421114395319916),
 (1306, 0.09421114395319916),
 (1884, 0.09421114395319916),
 (1942, 0.09421114395319916),
 (2053, 0.09421114395319916),
 (3902, 0.09421114395319916),
 (4019, 0.09421114395319916),
 (4205, 0.09421114395319916),
 (4493, 0.09421114395319916),
 (4548, 0.09370791409872918),
 (412, 0.09342836717341034),
 (932, 0.09342836717341034),
 (2702, 0.09342836717341034),
 (3621, 0.09342836717341034),
 (18, 0.0930725988812425),
 (239, 0.0930725988812425),
 (371, 0.09245003270420486),
 (1276, 0.09245003270420486),
 (2650, 0.09245003270420486),
 (4486, 0.09245003270420486),
 (33, 0.09245003270420485),
 (148, 0.09245003270420485),
 (362, 0.09245003270420485),
 (715, 0.09245003270420485),
 (791, 0.09245003270420485),
 (1686, 0.09245003270420485),
 (1721, 0.09245003270420485),
 (2562, 0.09245003270420485),
 (4007, 0.09245003270420485),
 (4258, 0.09245003270420485),
 (4405, 0.09245003270420485),
 (4475, 0.09245003270420485),
 (814, 0.0915018021743355),
 (1357, 0.0915018021743355),
 (1692, 0.0915018021743355),
 (4020, 0.0915018021743355),
 (219, 0.09078412990032037),
 (660, 0.09078412990032037),
 (1573, 0.09078412990032037),
 (2396, 0.09078412990032037),
 (2645, 0.09078412990032037),
 (3538, 0.09078412990032037),
 (785, 0.09065471553673685),
 (799, 0.09065471553673685),
 (243, 0.09058216273156766),
 (473, 0.09058216273156766),
 (813, 0.09058216273156766),
 (1446, 0.09058216273156766),
 (1906, 0.09058216273156766),
 (2488, 0.09058216273156766),
 (2592, 0.09058216273156766),
 (3408, 0.09058216273156766),
 (43, 0.08968970586617499),
 (596, 0.08968970586617499),
 (602, 0.08968970586617499),
 (1233, 0.08968970586617499),
 (1701, 0.08968970586617499),
 (12, 0.08920515501750789),
 (167, 0.08920515501750789),
 (511, 0.08920515501750789),
 (920, 0.08920515501750789),
 (1474, 0.08920515501750789),
 (1756, 0.08920515501750789),
 (2093, 0.08920515501750789),
 (4333, 0.08920515501750789),
 (2570, 0.08896008544727063),
 (331, 0.0888231183368655),
 (2797, 0.0888231183368655),
 (3721, 0.0888231183368655),
 (4037, 0.0888231183368655),
 (274, 0.08861469461982083),
 (1169, 0.08798117404291673),
 (1846, 0.08798117404291673),
 (2363, 0.08798117404291673),
 (2115, 0.08788174152965353),
 (244, 0.08770580193070292),
 (292, 0.08770580193070292),
 (356, 0.08770580193070292),
 (400, 0.08770580193070292),
 (980, 0.08770580193070292),
 (1259, 0.08770580193070292),
 (1589, 0.08770580193070292),
 (2251, 0.08770580193070292),
 (2651, 0.08770580193070292),
 (2660, 0.08770580193070292),
 (3737, 0.08770580193070292),
 (618, 0.08716272672808179),
 (1783, 0.08716272672808179),
 (3390, 0.08716272672808179),
 (169, 0.0863667034175061),
 (199, 0.0863667034175061),
 (270, 0.0863667034175061),
 (997, 0.0863667034175061),
 (2741, 0.0863667034175061),
 (3557, 0.0863667034175061),
 (3882, 0.0863667034175061),
 (2448, 0.08633531446374632),
 (141, 0.08627959628145762),
 (389, 0.08627959628145762),
 (564, 0.08627959628145762),
 (1427, 0.08627959628145762),
 (1480, 0.08627959628145762),
 (2869, 0.08627959628145762),
 (2958, 0.08627959628145762),
 (301, 0.08583770043743413),
 (752, 0.08559209850218259),
 (1629, 0.08559209850218259),
 (1832, 0.08559209850218259),
 (2109, 0.08559209850218259),
 (3463, 0.08559209850218259),
 (4505, 0.08559209850218259),
 (479, 0.08534859274986485),
 (23, 0.08492077756084468),
 (457, 0.08492077756084468),
 (745, 0.08492077756084468),
 (794, 0.08492077756084468),
 (960, 0.08492077756084468),
 (1134, 0.08492077756084468),
 (1249, 0.08492077756084468),
 (3136, 0.08492077756084468),
 (3323, 0.08492077756084468),
 (3450, 0.08492077756084468),
 (4757, 0.08492077756084468),
 (827, 0.08483796839677037),
 (3554, 0.08483796839677037),
 (129, 0.084103426706236),
 (2354, 0.084103426706236),
 (2472, 0.084103426706236),
 (2, 0.08362420100070908),
 (88, 0.08362420100070908),
 (2261, 0.08362420100070908),
 (3449, 0.08362420100070908),
 (1097, 0.08362420100070907),
 (32, 0.08338763984501665),
 (234, 0.08338763984501665),
 (1639, 0.08338763984501665),
 (2969, 0.08338763984501665),
 (48, 0.0826898230594723),
 (217, 0.0826898230594723),
 (381, 0.0826898230594723),
 (1305, 0.0826898230594723),
 (1530, 0.0826898230594723),
 (2857, 0.0826898230594723),
 (4355, 0.0826898230594723),
 (1, 0.08238525545716345),
 (2304, 0.08238525545716345),
 (2500, 0.08238525545716345),
 (4563, 0.08238525545716345),
 (79, 0.08200923681047297),
 (190, 0.08200923681047297),
 (403, 0.08200923681047297),
 (963, 0.08200923681047297),
 (2386, 0.0817150563075767),
 (19, 0.08134518347820842),
 (315, 0.081199794294115),
 (547, 0.081199794294115),
 (775, 0.081199794294115),
 (894, 0.081199794294115),
 (1142, 0.081199794294115),
 (1378, 0.081199794294115),
 (1688, 0.081199794294115),
 (2583, 0.081199794294115),
 (3348, 0.081199794294115),
 (3471, 0.081199794294115),
 (2203, 0.0806970043558403),
 (3906, 0.0806970043558403),
 (39, 0.08006407690254357),
 (45, 0.08006407690254357),
 (62, 0.08006407690254357),
 (63, 0.08006407690254357),
 (142, 0.08006407690254357),
 (152, 0.08006407690254357),
 (203, 0.08006407690254357),
 (241, 0.08006407690254357),
 (341, 0.08006407690254357),
 (501, 0.08006407690254357),
 (534, 0.08006407690254357),
 (787, 0.08006407690254357),
 (1103, 0.08006407690254357),
 (1207, 0.08006407690254357),
 (1325, 0.08006407690254357),
 (2167, 0.08006407690254357),
 (3141, 0.08006407690254357),
 (3181, 0.08006407690254357),
 (3219, 0.08006407690254357),
 (3302, 0.08006407690254357),
 (3528, 0.08006407690254357),
 (3979, 0.08006407690254357),
 (4519, 0.08006407690254357),
 (4571, 0.08006407690254357),
 (4590, 0.08006407690254357),
 (4629, 0.08006407690254357),
 (4644, 0.08006407690254357),
 (4660, 0.08006407690254357),
 (4674, 0.08006407690254357),
 (4793, 0.08006407690254357),
 (1346, 0.07944581222989573),
 (16, 0.07897471897389846),
 (37, 0.07897471897389846),
 (164, 0.07897471897389846),
 (242, 0.07897471897389846),
 (245, 0.07897471897389846),
 (306, 0.07897471897389846),
 (402, 0.07897471897389846),
 (626, 0.07897471897389846),
 (854, 0.07897471897389846),
 (901, 0.07897471897389846),
 (1519, 0.07897471897389846),
 (1747, 0.07897471897389846),
 (2128, 0.07897471897389846),
 (2644, 0.07897471897389846),
 (2661, 0.07897471897389846),
 (2866, 0.07897471897389846),
 (3765, 0.07897471897389846),
 (3852, 0.07897471897389846),
 (3927, 0.07897471897389846),
 (486, 0.07888947910127372),
 (38, 0.07884165279854434),
 (1534, 0.07884165279854434),
 (2793, 0.07884165279854434),
 (4509, 0.07884165279854434),
 (51, 0.0782510703046739),
 (222, 0.0782510703046739),
 (1828, 0.0782510703046739),
 (4078, 0.0782510703046739),
 (2224, 0.07792865001991967),
 (2684, 0.07792865001991967),
 (103, 0.07767356373806174),
 (776, 0.07767356373806174),
 (812, 0.07767356373806174),
 (1664, 0.07767356373806174),
 (1698, 0.07767356373806174),
 (1898, 0.07767356373806174),
 (2549, 0.07767356373806174),
 (2672, 0.07767356373806174),
 (2878, 0.07767356373806174),
 (4281, 0.07767356373806174),
 (4657, 0.07767356373806174),
 (4740, 0.07767356373806174),
 (193, 0.07740086460344697),
 (1926, 0.07710865759549869),
 (112, 0.07692307692307693),
 (329, 0.07692307692307693),
 (899, 0.07692307692307693),
 (1080, 0.07692307692307693),
 (1113, 0.07692307692307693),
 (1161, 0.07692307692307693),
 (1269, 0.07692307692307693),
 (2295, 0.07692307692307693),
 (4318, 0.07692307692307693),
 (153, 0.07655590023509527),
 (1282, 0.07655590023509527),
 (286, 0.07601486235852867),
 (3561, 0.07601486235852867),
 (174, 0.075955452531275),
 (349, 0.075955452531275),
 (737, 0.075955452531275),
 (922, 0.075955452531275),
 (1289, 0.075955452531275),
 (1719, 0.075955452531275),
 (2939, 0.075955452531275),
 (3029, 0.075955452531275),
 (3103, 0.075955452531275),
 (3165, 0.075955452531275),
 (3167, 0.075955452531275),
 (3234, 0.075955452531275),
 (4343, 0.075955452531275),
 (4627, 0.075955452531275),
 (866, 0.07548513560963972),
 (1139, 0.07548513560963972),
 (1621, 0.07548513560963972),
 (1924, 0.07548513560963972),
 (2339, 0.07548513560963972),
 (2713, 0.07548513560963972),
 (3729, 0.07548513560963972),
 (3833, 0.07548513560963972),
 (4476, 0.07548513560963972),
 (4495, 0.07548513560963972),
 (96, 0.07502344849205331),
 (492, 0.07502344849205331),
 (632, 0.07502344849205331),
 (1290, 0.07502344849205331),
 (2219, 0.07502344849205331),
 (3092, 0.07502344849205331),
 (4270, 0.07502344849205331),
 (246, 0.074458079104994),
 (1659, 0.074458079104994),
 (3332, 0.07433762918125657),
 (82, 0.07412493166611012),
 (98, 0.07412493166611012),
 (101, 0.07412493166611012),
 (207, 0.07412493166611012),
 (235, 0.07412493166611012),
 (395, 0.07412493166611012),
 (503, 0.07412493166611012),
 (1293, 0.07412493166611012),
 (1523, 0.07412493166611012),
 (2021, 0.07412493166611012),
 (2449, 0.07412493166611012),
 (2917, 0.07412493166611012),
 (3817, 0.07412493166611012),
 (4046, 0.07412493166611012),
 (4561, 0.07412493166611012),
 (2005, 0.07396002616336388),
 (125, 0.0736876126183612),
 (584, 0.0734718358370645),
 (858, 0.0734718358370645),

In [47]:
def recommend(movie):
    movieIndex = newMovieDataFrame[newMovieDataFrame['title'] == movie].index[0]
    distances = similarity[movieIndex]
    moviesList = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    
    for i in moviesList:
        print(newMovieDataFrame.iloc[i[0]].title)

In [48]:
recommend('Predators')

Aliens vs Predator: Requiem
Meet Dave
Riddick
Star Trek: Insurrection
Aliens

In [49]:
import pickle

In [50]:
pickle.dump(newMovieDataFrame,open('movies.pkl','wb'))

In [51]:
pickle.dump(newMovieDataFrame.to_dict(),open('movies_dict.pkl','wb'))

In [52]:
pickle.dump(similarity,open('similarity.pkl','wb'))